t = input('Digite algo:')
print('O tipo primitivo desse valor e', type(t))
print('E um numero ?', t.isnumeric())
print('E alfabetico ?', t.isalpha())
print('E alphanumerico ?', t.isalnum())
print('Esta em letra maiuscula ?', t.isupper())
print('Esta em letra minuscula ?', t.lower())
print('Esta capitalizada ?', t.istitle())
print('So tem espaços ?', t.isspace())
